[package]
name = "pathify"
version = "0.1.0"
edition = "2021"
authors = ["load1n9"]

description = "Library to create a dependency tree"
repository = "https://github.com/load1n/pathify"
readme = "../README.md"

[dependencies]
url = "2.3.1"
reqwest = { version = "0.11.14", features = ["blocking"] }